# Generated by Django 3.0.7 on 2020-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200626_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст комментария'),
        ),
    ]
