# Generated by Django 3.0.7 on 2020-06-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200626_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Отзывов', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
